### ISSUE TITLE
Feature request: Copy snapshots to remote server

### ISSUE THREAD

**Issue by ghost** [Patryk27/lxd-snapper#5]
I understand that this might be outside the scope of the project, but it would be amazing if copying snapshots to a remote server was supported. The current tools to do this with lxd alone is very lackluster!

**Comment by Patryk27** [comment]
Hmm, how about hooks?

I imagine you'd do something like:

```yaml
hooks:
  on-snapshot-created: "./copy-snapshot {snapshotName}"
  on-snapshot-deleted: "./delete-snapshot {snapshotName}"
```

... and then lxd-snapper would simply run that script / command when a snapshot gets created / deleted; paired with [`zfs send | ssh zfs recv`](https://docs.oracle.com/cd/E18752_01/html/819-5461/gbchx.html) this would allow to sync snapshots without having to call other tools such as Sanoid.

**Comment by ghost** [comment]
Something like that could work!

**Comment by OhSoGood** [comment]
Hi, 
I use a separate cron today to remotely copy snapshots, and I find this request super cool, so a big thank for implementing it (and for the whole tool, by the way!).

Yet, I wonder if triggering a remote copy on the event on-snapshot-created is the right way: if the remote copy itself is slower that the time needed to take a snapshot, or even much slower (which seems a realistic scenario, WAN links being much slower than local drive I/O), we may end up with several remote copies in parallel, competing against each other. So, it could be useful to also have an event like 'on-all-snapshots-done' ?

**Comment by Patryk27** [comment]
Hi, thanks for pitching in - yes, that's a fair point; how about if you could specify per hook whether it should be immediate (= run right after `lxc snapshot` completes) or delayed (i.e. run after all of the snapshots were created)?
```yaml
hooks:
  on-snapshot-created:
    run: "./copy-snapshot {snapshotName}"
    mode: "immediate" | "delayed"
  on-snapshot-deleted:
    run: "./delete-snapshot {snapshotName}"
    mode: "immediate" | "delayed"
```
The difference between this approach and using a separate `on-all-snapshots-done` hook is that `on-snapshot-created` with `mode: delayed` would still be run `n` times (depending on how many snapshots were created; but always one after another, not all at once), just not directly after each snapshot, but rather after everything's been completed; would that come useful to you?

There's one case where `on-all-snapshots-created` could come useful on its own, and it's where one would like to sync all of the snapshots at once (i.e. have their script called just once) - for that, I was thinking about:

```yaml
hooks:
  backup:
    on-command-started:
      run: "rm -f /tmp/snapshots.txt"
    on-snapshot-created:
      run: "echo {snapshotName} >> /tmp/snapshots.txt"
    on-command-completed:
      run: "./sync-snapshots /tmp/snapshots.txt"
```

Whaddya think?
